# Generated by Django 2.0.6 on 2018-06-08 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'gliders',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
            options={
                'db_table': 'missions',
            },
        ),
        migrations.CreateModel(
            name='MissionGlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('dives', models.IntegerField(default=0)),
                ('glider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.Glider')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.Mission')),
            ],
            options={
                'db_table': 'mission_gliders',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
        migrations.CreateModel(
            name='SensorCalibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dark', models.FloatField()),
                ('scale', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.Sensor')),
            ],
            options={
                'db_table': 'sensor_calibrations',
            },
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'sensor_types',
            },
        ),
        migrations.AddField(
            model_name='sensorcalibration',
            name='sensorType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.SensorType'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.SensorType'),
        ),
        migrations.AddField(
            model_name='missionglider',
            name='sensors',
            field=models.ManyToManyField(db_table='mission_glider_sensors', to='management_system.Sensor'),
        ),
        migrations.AddField(
            model_name='mission',
            name='gliders',
            field=models.ManyToManyField(through='management_system.MissionGlider', to='management_system.Glider'),
        ),
    ]
