# Generated by Django 2.0.6 on 2018-06-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glider',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='missionglider',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='missionglider',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
